Superheroes/Models/Superhero.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Superheroes.Models
{
    public class Superhero
    {
        [Key]
        public int ID { get; set; }
        [Display(Name = "Name")]
        public string Name { get; set; }
        [Display(Name="Alter Ego")]
        public string alterEgo { get; set; }
        [Display(Name = "Primary Ability")]
        public string primaryAbility { get; set; }
        [Display(Name = "Secondary Ability")]
        public string secondaryAbility { get; set; }
        [Display(Name = "Catchphrase")]
        public string catchphrase { get; set; }
    }
}

Superheroes/Controllers/SuperheroController.cs
using Superheroes.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Superheroes.Controllers
{
    public class SuperheroController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Superhero
        public ActionResult Index()
        {
            return View(db.Superheroes.ToList());
        }

        // GET: Superhero/Details/5
        public ActionResult Details(int id)
        {
            Superhero superhero = db.Superheroes.Where(s => s.ID == id).FirstOrDefault();
            return View(superhero);
        }

        // GET: Superhero/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Superhero/Create
        [HttpPost]
        public ActionResult Create(Superhero superhero)
        {
            try
            {
                // TODO: Add insert logic here
                db.Superheroes.Add(superhero);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View("Index");
            }
        }

        // GET: Superhero/Edit/5
        public ActionResult Edit(int id)
        {
            Superhero superhero = db.Superheroes.Where(s => s.ID == id).FirstOrDefault();
            return View(superhero);
        }

        // POST: Superhero/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Superhero superhero)
        {
            try
            {
                // TODO: Add update logic here
                Superhero superheroFromDb = db.Superheroes.Where(s => s.ID == id).FirstOrDefault();
                superheroFromDb.Name = superhero.Name;
                superheroFromDb.alterEgo = superhero.alterEgo;
                superheroFromDb.primaryAbility = superhero.primaryAbility;
                superheroFromDb.secondaryAbility = superhero.secondaryAbility;
                superheroFromDb.catchphrase = superhero.catchphrase;

                db.SaveChanges();
                return RedirectToAction("Details", new { id = superhero.ID });
            }
            catch
            {
                return View();
            }
        }

        // GET: Superhero/Delete/5
        public ActionResult Delete(int id)
        {
            Superhero superhero = db.Superheroes.Where(s => s.ID == id).FirstOrDefault();
            return View(superhero);
        }

        // POST: Superhero/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Superhero superhero)
        {
            try
            {
                // TODO: Add delete logic here
                Superhero superheroFromDb = db.Superheroes.Where(s => s.ID == id).FirstOrDefault();
                db.Superheroes.Remove(superheroFromDb);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Superheroes/Views/Superhero/Create.cshtml
@model Superheroes.Models.Superhero

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Superheroes</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, "Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.alterEgo, "Alter Ego", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.alterEgo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.alterEgo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.primaryAbility, "Primary Ability", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.primaryAbility, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.primaryAbility, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.secondaryAbility, "Secondary Ability", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.secondaryAbility, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.secondaryAbility, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.catchphrase, "Catchphrase", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.catchphrase, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.catchphrase, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

    <div>
        @Html.ActionLink("Back to List", "Index", "Superhero")
    </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Superheroes/Views/Superhero/Delete.cshtml
@model Superheroes.Models.Superhero

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Superheroes</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.alterEgo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.alterEgo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.primaryAbility)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.primaryAbility)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.secondaryAbility)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.secondaryAbility)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.catchphrase)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.catchphrase)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index", "Home")
        </div>
    }
</div>

Superheroes/Views/Superhero/Details.cshtml
@model Superheroes.Models.Superhero

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Superheroes</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.alterEgo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.alterEgo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.primaryAbility)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.primaryAbility)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.secondaryAbility)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.secondaryAbility)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.catchphrase)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.catchphrase)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Delete", "Delete", new { id = Model.ID }) |
    @Html.ActionLink("Back to Home", "Index", "Home")
</p>

Superheroes/Views/Superhero/Edit.cshtml
@model Superheroes.Models.Superhero

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Superheroes</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, "Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.alterEgo, "Alter Ego", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.alterEgo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.alterEgo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.primaryAbility, "Primary Ability", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.primaryAbility, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.primaryAbility, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.secondaryAbility, "Secondary Ability", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.secondaryAbility, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.secondaryAbility, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.catchphrase, "Catchphrase", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.catchphrase, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.catchphrase, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Superheroes/Views/Superhero/Index.cshtml
@model IEnumerable<Superheroes.Models.Superhero>

@{
    ViewBag.Title = "List of Heroes";
}

<h2>List of Heroes</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.alterEgo)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.primaryAbility)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.secondaryAbility)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.catchphrase)
        </th>*@
        <th> Options </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.alterEgo)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.primaryAbility)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.secondaryAbility)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.catchphrase)
        </td>*@
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>